<a href="https://colab.research.google.com/github/area409/OpenSourceKeras/blob/master/02_oss_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###한림대학교 소프트웨어 융합 대학 특강

##누구나 즐기는 딥러닝: 오픈소스 Keras를 활용하여!!!

이정근 교수

빅데이터전공주임/오픈소스소프트웨어센터장 소프트웨어융합대학

jeonggun.lee@hallym.ac.kr 2019년 5월


---


###Keras 딥러닝: AND 논리 함수


In [0]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np 

data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outcome = np.array([[0], [0], [0], [1]])

model = Sequential()
model.add(Dense(1, input_dim=2))


Using TensorFlow backend.
UsageError: Line magic function `%data` not found.


In [0]:
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(data, outcome, epochs=1000, batch_size=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
4/4 [==============================] - 2s 620ms/step - loss: 1.2051
Epoch 2/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.1926
Epoch 3/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.1791
Epoch 4/1000
4/4 [==============================] - 0s 2ms/step - loss: 1.1648
Epoch 5/1000
4/4 [==============================] - 0s 2ms/step - loss: 1.1483
Epoch 6/1000
4/4 [==============================] - 0s 2ms/step - loss: 1.1387
Epoch 7/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.1227
Epoch 8/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.1117
Epoch 9/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.0969
Epoch 10/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.0844
Epoch 11/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.0724
Epoch 12/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.0608

In [0]:
model.predict(data)

array([[-0.29570773],
       [ 0.24371263],
       [ 0.23912385],
       [ 0.7785442 ]], dtype=float32)

## Sigmoid 활성 함수 사용

좀더 성능을 끌어올릴 수 있는 방법으로 활성화 함수를 사용해보겠습니다.

AND 함수의 경우 출력이 0 또는 1에 해당하기 때문에, **sigmoid** 함수를 사용하도록 하겠습니다.


---



---



In [0]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np 

data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outcome = np.array([[0], [0], [0], [1]])

model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(data, outcome, epochs=1000, batch_size=1)

model.predict(data)

Epoch 1/1000
4/4 [==============================] - 0s 27ms/step - loss: 0.2779
Epoch 2/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2774
Epoch 3/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2772
Epoch 4/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2770
Epoch 5/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2769
Epoch 6/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2766
Epoch 7/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2765
Epoch 8/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2763
Epoch 9/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.2762
Epoch 10/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2759
Epoch 11/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2758
Epoch 12/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2756
Epoch 13/1000
4/4 [=============================

array([[0.27338874],
       [0.29821903],
       [0.40669852],
       [0.43636525]], dtype=float32)

## 성능 향상을 위한 다층 신경망 구성

층의 수를 좀더 늘려볼까요 ?


---



---



In [0]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np 

data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outcome = np.array([[0], [0], [0], [1]])

model = Sequential()
model.add(Dense(8, input_dim=2, activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(data, outcome, epochs=1000, batch_size=1)

model.predict(data)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.


Epoch 1/1000
4/4 [==============================] - 0s 39ms/step - loss: 0.2494
Epoch 2/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2485
Epoch 3/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.2483
Epoch 4/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2479
Epoch 5/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2475
Epoch 6/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2473
Epoch 7/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2470
Epoch 8/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2467
Epoch 9/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2467
Epoch 10/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2462
Epoch 11/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2459
Epoch 12/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2456
Epoch 13/1000
4/4 [=============================

array([[0.01967815],
       [0.11979541],
       [0.06792986],
       [0.89515114]], dtype=float32)

## 성능 향상을 위한 깊은 (?) 신경망 구성

층의 수를 하나 더 늘려 볼까요 ?


---



---



In [0]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np 

data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outcome = np.array([[0], [0], [0], [1]])

model = Sequential()
model.add(Dense(8, input_dim=2, activation='relu'))
model.add(Dense(4, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(data, outcome, epochs=1000, batch_size=1)

model.predict(data)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(4, activation="relu", kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()


Epoch 1/1000
4/4 [==============================] - 0s 49ms/step - loss: 0.2499
Epoch 2/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.2496
Epoch 3/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2494
Epoch 4/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2492
Epoch 5/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2488
Epoch 6/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2486
Epoch 7/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2483
Epoch 8/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2480
Epoch 9/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2478
Epoch 10/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2476
Epoch 11/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2473
Epoch 12/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2469
Epoch 13/1000
4/4 [=============================

array([[0.00239092],
       [0.04349822],
       [0.0148949 ],
       [0.96746683]], dtype=float32)

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np 

data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outcome = np.array([[0], [0], [0], [1]])

model = Sequential()
model.add(Dense(8, input_dim=2, activation='relu'))
model.add(Dense(4, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam')
model.fit(data, outcome, epochs=1000, batch_size=1)

model.predict(data)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(4, activation="relu", kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()


Epoch 1/1000
4/4 [==============================] - 0s 73ms/step - loss: 0.6930
Epoch 2/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.6925
Epoch 3/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.6916
Epoch 4/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.6914
Epoch 5/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.6905
Epoch 6/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.6901
Epoch 7/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.6896
Epoch 8/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.6892
Epoch 9/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.6885
Epoch 10/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.6883
Epoch 11/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.6876
Epoch 12/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.6870
Epoch 13/1000
4/4 [=============================

array([[2.3454428e-05],
       [1.3621151e-03],
       [1.5155673e-03],
       [9.9668992e-01]], dtype=float32)